### ISSUE TITLE
CSRF token invalid on HTTP site

### ISSUE THREAD

**Issue by polistern** [hugmouse/vpub-plus#5]
Got follow error on login in HTTP site:

- Response:

```
Forbidden - CSRF token invalid
```

- Browser console:

```
Cookie "_gorilla_csrf" has been rejected because a non-HTTPS cookie can’t be set as "secure".
```

Looks like the CSRF token should be passed along with the forms.

**Comment by hugmouse** [comment]
Hello,

This happens because Gorilla uses secure context for cookies by default. For now, you can set your browser to ignore secure context if you are running it locally. 

But I think I can add a `DEV` environment variable that will disable secure context.

Please let me know what you think and if you have any other ideas!

**Comment by polistern** [comment]
Unfortunately, I can't advise you on the best practices in such situations and their applicability here in this case.

Regarding the browser settings, this can of course be useful in testing and development. But when used in production, it must be configured by anyone who wants to use the forum. And this already sounds strange :)

**Comment by hugmouse** [comment]
Hello once again,

You can now set the `CSRF_SECURE` environment variable to make the cookie's context secure or not. 
Use `CSRF_SECURE=true` to make it secure and `CSRF_SECURE=false` to make it... insecure? Yeah.

For now there is no release for it yet, so you have to use latest commit from the master branch.

**Comment by polistern** [comment]
Very strange, I still get an error when trying to login.

My assumption about the lack of a CSRF token in the form was wrong.  
I rechecked the code to the latest commits and there is a CSRF token in the login form.

In this case, well, I just do not understand why I get this error.

Below I will describe the settings of my test environment.

- ENV parameters:

```bash
export DATABASE_URL=...
export SESSION_KEY=b51ec78e0e0841d30c52c5d4fdc91bff
export CSRF_KEY=b8ddef4832c79907d711e55ef83697fc
export CSRF_SECURE=false
export TITLE="TEST"
export PORT=8888
```

- Nginx as a reverse proxy:

```
server {
    listen 80;
    server_name example.com;
    location / {
        proxy_pass http://127.0.0.1:8888;
    }
}
```

- domain `example.com` is set in `/etc/hosts` file.
- database is empty and was filled by the application at the first run.

Everything from scratch.


Can you try to reproduce the problem from your side?

**Comment by hugmouse** [comment]
Yes, I was able to reproduce it. 

Please take the last commit, compile it and try again. This should be fixed now.

As a side note, the `TITLE` environment variable does not seem to be used in the `vpub` codebase, so I removed it from the README to not to confuse anyone.

**Comment by polistern** [comment]
Hey, now it works!

Thanks!
